# Generated by Django 4.2 on 2023-04-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_course_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='thumbnail_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
