# Generated by Django 4.2 on 2023-04-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_course_thumbnail_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='thumbnail_link',
        ),
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
